### PR TITLE
Add extension for lyrics

### PR DESCRIPTION
**Pull request by Darkempire78**

### CODE REVIEW

**Review by 3raxton — COMMENTED** [review]
Thanks for opening a PR @Darkempire78! All of this is looking good to me. I want to ensure that the images show up on the repo, so I will go ahead and merge to the master branch but would like you to keep a lookout for future comments if the images will no load in the respective README (I don't expect there to be a problem). 

One question before merging, while it's not required, I'm trying to ensure this remains as community-oriented as it can. Would you like to add your name and a link to the [AUTHORS.md](https://github.com/3raxton/spicetify-custom-apps/blob/main/AUTHORS.md) file? If you'd let me know, that would be great. Then I'll go ahead and merge.

**Comment by Darkempire78** [comment]
No problem, you can add me on the Authors.md file.
I will also check the images

**Comment by 3raxton** [comment]
Sounds good. Unfortunately, I won't have the chance to add you to the file until later tonight. If you'd like to add yourself feel free but also know it's not required. Sorry for the delay.

**Comment by Darkempire78** [comment]
It should be good for images

**Comment by 3raxton** [comment]
All looks good, glad to have you as part of the repo!

**Comment by 3raxton** [comment]
Merged, merci!

**Pull request merged**
