### PR TITLE
Added two extensions (copy playlists, history shortcut)

### PR DESCRIPTION
**Pull request by einzigartigerName**

### CODE REVIEW

**Comment by 3raxton** [comment]
Hey @einzigartigerName, happy to have you as part of the repo! Commits are looking good to me. I haven't yet merged a README with images linked and laid out like yours but am going to merge anyway. I'll follow up if there are any issues. 

Thanks for the PR!

**Comment by 3raxton** [comment]
Following up, all looks good 🔥

**Comment by einzigartigerName** [comment]
Happy to be contribute 👍🏾

**Comment by 3raxton** [comment]
@einzigartigerName I've decided to separate the custom apps from extensions to make it easier for those looking for apps and extensions. Would you consider this to be an extension?

**Pull request merged**
