### PR TITLE
Add spicetify-hide-podcasts

### PR DESCRIPTION
**Pull request by theRealPadster**
Here's my custom extension. Since it's based on the ChristianSpotify extension from the main Spicetify repo, which is under GPL, I've included a note and the LICENSE file in my folder (since works based off GPL must also be distributed under GPL). I hope this is okay/legal, since it looks like you have the main repo under MIT. I've also included an initial try at the attribution note and markdown file. 

Let me know what you think!

### CODE REVIEW

**Review by 3raxton — CHANGES_REQUESTED** [review]
Hey @theRealPadster, thanks for making a PR! I finally had the chance to update the repo a bit more and add a file for attribution [AUTHORS.md](https://github.com/3raxton/spicetify-custom-apps/blob/main/AUTHORS.md); your ATTRIBUTION.md file helped inspire some of it!

That being said, I've added a specific layout for AUTHORS.md to ensure easy viewing for everyone who takes a look. Would you mind following that format as opposed to adding an attribution section to the README? You can find the details [here](https://github.com/3raxton/spicetify-custom-apps/blob/main/AUTHORS.md#are-you-adding-your-name-and-custom-app-to-this-file).

Let me know if you have any questions!

**Comment by theRealPadster** [comment]
@3raxton Could you take another look? I merged in your changes from upstream and I think I got rid of the stuff we don't want, but I'm not 100% sure. My question about the GPL license still stands as well. Just seems kinda weird for me to put a note about it in the AUTHORS.md, and have your blurb about the MIT license right underneath, but maybe that's fine? 🤷‍♂️

**Comment by 3raxton** [comment]
All is looking good to me! Sorry that I missed your question about the license from the other day; it should be fine. The MIT license only covers the collection of custom apps and providing them to spicetify users. As for your license, it shouldn't be a problem because it's contingent on your app. 

I'm no pro at licenses, so I can't say for sure, but I don't think we will run into any problems. [Here's a TLDR of the GPL license if you're interested](https://gist.github.com/kn9ts/cbe95340d29fc1aaeaa5dd5c059d2e60) (although I'm sure you know the license well). 

I'll be removing the license mention on the AUTHORS.md file; I used a template for it, which is why it's there. It covers the entire repo, so there's no need for me to have it mentioned in multiple areas. 

Thanks for the PR, it's merged!

**Comment by 3raxton** [comment]
Would love your opinion on one thing: 

What do you think about having a set folder for all the apps to clean up the look of the repo? (I would do all of this on my own, no need to make another PR)

**Comment by theRealPadster** [comment]
Awesome, sounds good! I think having a folder to keep all the apps in is a good idea. That way it doesn't get too out of hand when more are added.

**Pull request merged**
